### ISSUE TITLE
Does the code have corresponding paper?

### ISSUE THREAD

**Issue by liu09114** [leVirve/lsun-room#1]
Or do you have a result like room layout image?

**Comment by yyong119** [comment]
It seems to be a part of IM2CAD(chapter3.1 in the paper. Use LSUN dataset and Fully Convolutional Networks to label each pixel). Or maybe it's just a coincidence.

**Comment by leVirve** [comment]
@liu09114 We've updated the project though, and it's still in progress.

@yyong119 Nope, not really. There have been several FCN-like approaches for layout estimation. And IM2CAD use roughly the same idea in DeLay (Dasgupta _et al._) for this part. Our design is inspired more by ST-PIO (Zhao _et al._).

May refer,
http://lsun.cs.princeton.edu/leaderboard/index_2016.html#roomlayout
http://lsun.cs.princeton.edu/leaderboard/index.html#roomlayout

**Comment by liu09114** [comment]
@leVirve Thank you. I found that few ground truth label mistakes in the LSUN datasets, did you correct them?

**Comment by leVirve** [comment]
Yes, there are some mislabeled layouts in original LSUN Room, and we correct them manually.

**Comment by fanser** [comment]
@leVirve Could you release your relabeled layouts? Thx

**Comment by SpencerKD** [comment]
could you please share the labeled LSUN dataSet about the room , I 'll be very very thankful to your help!!!!!        And my email adress is :   t.f-zhan@foxmail.com
