### ISSUE TITLE
Ground truth data for raw images

### ISSUE THREAD

**Issue by lebeli** [leVirve/lsun-room#11]
Could you provide the ground truth data for the raw image input?

**Comment by huangshizhong** [comment]
> Could you provide the ground truth data for the raw image input?
Did you solve  this problem?

**Comment by lebeli** [comment]
Yes, I found the .mat files with the ground truth data.

**Comment by huangshizhong** [comment]
> Yes, I found the .mat files with the ground truth data.

how did you find the data ,i dont kown how to get the data ,could you supply the link or upload the data

**Comment by lebeli** [comment]
https://web.archive.org/web/20190118150204/http://lsun.cs.princeton.edu/2016/

**Comment by huangshizhong** [comment]
> https://web.archive.org/web/20190118150204/http://lsun.cs.princeton.edu/2016/

thanks for your help,but when i run the main.py ,there be a mistake :+1: FileNotFoundError: [Errno 2] No such file or directory: '/home/user/PycharmProjects/lr2018/lsun-room-2018.jan/data/lsun_room/training.mat'                    training.mat is download from your link or is the author supply.....And Could you share main.py usage example as it's getting difficult for me to understand arguments of it..Thank you very much

**Comment by huangshizhong** [comment]
> https://web.archive.org/web/20190118150204/http://lsun.cs.princeton.edu/2016/

thanks for your help,but when i run the main.py ,there be a mistake +1 FileNotFoundError: [Errno 2] No such file or directory: '/home/user/PycharmProjects/lr2018/lsun-room-2018.jan/data/lsun_room/training.mat' training.mat is download from your link or is the author supply.....And Could you share main.py usage example as it's getting difficult for me to understand arguments of it..Thank you very much

**Comment by leVirve** [comment]
@huangshizhong  It seems you have absolute path, and you might need to check the path first.
