### ISSUE TITLE
AttributeError: module 'onegan' has no attribute 'utils'

### ISSUE THREAD

**Issue by huangshizhong** [leVirve/lsun-room#12]
thanks for your code ,when i run the lsun_room demo.py there is a AttributeError: module 'onegan' has no attribute 'utils',but i have installed the Onegan 0.5.1, and i have found a test_utils.py in the onegan test test_data file , could you suplly the utils tank you very much @leVirve @nafmichael

**Comment by leVirve** [comment]
Rely in https://github.com/leVirve/lsun-room/issues/8#issuecomment-773359178. Thanks for report.
