### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/lsun_room/training.mat

### ISSUE THREAD

**Issue by Hui-Yao** [leVirve/lsun-room#14]
FileNotFoundError: [Errno 2] No such file or directory: '../data/lsun_room/training.mat

**Comment by leVirve** [comment]
You need to download that file from dataset first. You may refer to this https://web.archive.org/web/20190118150204/http://lsun.cs.princeton.edu/2016/ provided by https://github.com/leVirve/lsun-room/issues/11#issuecomment-721743008.

And make sure edit the path: https://github.com/leVirve/lsun-room/blob/master/config.yml#L8
