### ISSUE TITLE
main.py usage example

### ISSUE THREAD

**Issue by prashant0079** [leVirve/lsun-room#3]
Could you share main.py usage example as it's getting difficult for me to understand arguments of it and also how layout_seg_images will be generated?

**Comment by leVirve** [comment]
Sorry for late response. The images for `layout_seg_images` are converted from the dataset's `*.mat` file directly. And we are going to improve our readme document soon, thank you for your interests in our work. 😄

**Comment by Nethika** [comment]
LSUN provides a *.mat file? Couldn't find from where to download. Can you please provide a link.

**Comment by leVirve** [comment]
@Nethika Yes, they do. The dataset is available at http://lsun.cs.princeton.edu/2015.html#layout and the layout ground truth in `layout.zip`.

**Comment by Nethika** [comment]
Thank You!

**Comment by SpencerKD** [comment]
the dataset cant be downloaded from the link:  http://lsun.cs.princeton.edu/2015.html#layout, because the link is 404

**Comment by SpencerKD** [comment]
> Thank You!
Have you downloaded the LSUN dataset? And can you share it?

**Comment by huangshizhong** [comment]
> Thank You!

hello,did you get the data,could you suplly the link or data

**Comment by leVirve** [comment]
Hi guys, please refer to the updated readme for the dataset https://github.com/leVirve/lsun-room#dataset
