### ISSUE TITLE
from trainer.賣扣老師 import build_resnet101_FCN

### ISSUE THREAD

**Issue by pjspillai** [leVirve/lsun-room#5]
Getting Error:

Can't find trainer.賣扣老師

**Comment by leVirve** [comment]
Duplicated with #4.

Some files have been modified, and we will update the code base as we're permitted. But, you now can try to replace them with

```python
# Old
from trainer.賣扣老師 import build_resnet101_FCN
model = build_resnet101_FCN(pretrained=False, nb_classes=37, stage_2=True, joint_class=joint_class)

# Use this instead
from trainer.model import ResPlanarSeg
model = ResPlanarSeg(num_classes=5, pretrained=False)
```

**Comment by pjspillai** [comment]
I did that, now I am getting a different error:

  File "/home/ppillai/anaconda3/envs/torch/lib/python3.6/site-packages/torch/serialization.py", line 172, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

**Comment by leVirve** [comment]
Seems that you run the script without argument `weight_path`, and you need to train the network first.

**Comment by SpencerKD** [comment]
I want to train the network, but unfortunately，I cant find the LSUN DataSet anywhere. So can you upload the pretrained model or the LSUN dataset for the semantic segmentation，many thanks

**Comment by huangshizhong** [comment]
> I want to train the network, but unfortunately，I cant find the LSUN DataSet anywhere. So can you upload the pretrained model or the LSUN dataset for the semantic segmentation，many thanks

do you solve this problem ,i have the same error,i would be very grateful for  you to tell me how to solve this problem

**Comment by leVirve** [comment]
Unfortunately, the challenge website is down 😢 , am trying to find other resources for that.

**Comment by leVirve** [comment]
Hi guys, please refer to the updated readme for the dataset https://github.com/leVirve/lsun-room#dataset
