### ISSUE TITLE
ModuleNotFoundError: No module named 'onegan.utils'

### ISSUE THREAD

**Issue by sairajab** [leVirve/lsun-room#8]
This is error I get when I try to run 0ython main.py .. OneGAN module does not have any repository utils that contain defination for to-var. Kindly help

**Comment by sairajab** [comment]
Solved: You need to download previous versions of onegan may be 3.2.0

**Comment by pumpkinsue** [comment]
Can you give more details about how to download previous versions of onegan? Kindly help

**Comment by huangshizhong** [comment]
> Solved: You need to download previous versions of onegan may be 3.2.0

where and  hao to download onegan 3.2.0

**Comment by Hui-Yao** [comment]
> Solved: You need to download previous versions of onegan may be 3.2.0
ModuleNotFoundError: No module named 'onegan.metrics',,,,,,how to solve it

**Comment by leVirve** [comment]
Hi, guys
Here's the OneGAN v0.3.2 that works for this project. Can direct download and install from https://github.com/leVirve/OneGan/releases/tag/0.3.2, or clone that repository then checkout with `git checkout 0.3.2`.
