### ISSUE TITLE
Request for the article

### ISSUE THREAD

**Issue by GalAvineri** [leVirve/lsun-room#9]
Can you please provide a link to the article which describes the algorithm? :)

**Comment by shuuchen** [comment]
+1

**Comment by OnlyRightNow** [comment]
https://homes.cs.washington.edu/~izadinia/files/im2cad_CVPR17.pdf

**Comment by leVirve** [comment]
@OnlyRightNow That's not my paper :-P 
You can find it on https://ieeexplore.ieee.org/document/8546278.

**Comment by leVirve** [comment]
Thanks @shuuchen! Here's another link https://github.com/shuuchen/lsun-room-dsc/blob/master/layout_lin.pdf.
